name: raw_api_server
description: A Dart package for small and simple socket-based APIs
version: 1.0.1
repository: https://www.github.com/tytydraco/raw_api_server

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  path: ^1.8.0
  collection: ^1.16.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
